server:
  port: 8081
  contextPath: /api
  session:
    timeout: 86400
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath*:top/icoding/**/mapper/*Mapper.xml
spring:
  http:
    encoding:
      charset: utf8
  session:
    store-type: redis
  redis:
    database: 0
    host: 39.106.214.109
    port: 6379
    password: icoding
  datasource:
    url: jdbc:mysql://39.106.214.109:3306/icoding?characterEncoding=utf8&useSSL=true
    username: icoding
    password: icoding
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
social:
  qqAppId: 101452871
  qqAppSecret: be505fe2be87a95faefddcbd10c3b25c
  githubAppId: 8347be17a991df62767f
  githubAppSecret: 9f502ba54524fe6f7977db90b8ed38d887adf7d0
qiniu:
  accessKey: uZ_EKH3PFdDR4jw9Hsp1v6Zb6BiqPueoD2Xd1IEp
  secretKey: wWHCOsSbPIGGtCCSOzto0anPgUpkzgd92lfCE290
  bucket: icode