server:
  port: 8081
  contextPath: /api
  session:
    timeout: 86400
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath*:top/icoding/**/mapper/*Mapper.xml
spring:
  http:
    encoding:
      charset: utf8
  session:
    store-type: redis
  redis:
    database: 0
    host:
    port:
    password:
  datasource:
    url:
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
social:
  qqAppId:
  qqAppSecret:
  githubAppId:
  githubAppSecret:
qiniu:
  accessKey:
  secretKey:
  bucket: