server:
  port: 80
  contextPath: /
  session:
    timeout: 600
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath*:top/icoding/**/mapper/*Mapper.xml
spring:
  http:
    encoding:
      charset: utf8
  session:
    store-type: redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/icoding?characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
 